### ISSUE TITLE
AutomationHAT contribution

### ISSUE THREAD

**Issue by shortbloke** [pimoroni/node-red-nodes#3]
I'm working on an implementation for the AutomationHAT (https://github.com/shortbloke/node-red-nodes/tree/automationhat). I've initially started this as a fork. However I can see that you have a link out to 3rd party nodes contributions. From this can I assume that you'd not want to accept a PR to add this support into your main package and instead I should follow the example of: https://github.com/cyberflohr/node-red-contrib-rainbow-hat

Thanks Martin

**Comment by Gadgetoid** [comment]
You assume correctly- as much as I'd love to accept a PR and take this under our wing, right now I just don't know enough about NodeJS and Node-RED for it to be worth doing so.

**Comment by shortbloke** [comment]
Thanks, good to know. I'll restructure my project with a view to being a 3rd party node contribution.

**Comment by shortbloke** [comment]
@Gadgetoid I've created the Automation HAT implementation and raised a PR #4 to request an update to the readme to link out to this 3rd party implementation. The package is also published via npm.

**Comment by shortbloke** [comment]
PR Approved. Closing
